"""Build the editable, entirely vector graphical abstract from verified local data.

Run from any directory with Python plus NumPy and pandas installed.  The plot is
the corrected-loading EnergyPhasePINN LOCO fold 0, seed 0, 800-epoch run saved by
generate_figure_data.py.  It uses all 557 saved predictions without smoothing.
The bottom metrics summarize all 18 folds x 5 seeds, not this example curve.
"""

from __future__ import annotations

import html
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

import numpy as np


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))
import revision_data as data  # noqa: E402


INK = "#183243"
MUTED = "#607582"
BLUE = "#0072B2"
TEAL = "#008878"
ORANGE = "#D55E00"
BORDER = "#D9E3E8"
PALE_BLUE = "#F0F6FA"
PALE_TEAL = "#EDF7F3"
PALE_WARM = "#FDF3EC"
W, H = 1600, 850
MATH_FONT = "Cambria, Times New Roman, serif"


class SVG:
    def __init__(self):
        self.parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="183mm" '
            f'height="{183 * H / W:.5f}mm" viewBox="0 0 {W} {H}" '
            'font-family="Arial, Helvetica, sans-serif" role="img" '
            'aria-labelledby="figure-title figure-description">',
            '<title id="figure-title">Energy-based learning of nanoindentation</title>',
            '<desc id="figure-description">AlCuNiTiZr high-entropy-alloy molecular-dynamics '
            'loading data feed elastic, plastic and hardening energy branches with smooth '
            'depth-dependent regime weights and a learned residual energy. The predicted force '
            'is the full depth derivative of their scalar loading potential. The right-hand '
            'plot shows the actual held-out curve for LOCO fold 0, seed 0: 557 corrected '
            'loading points, grain size 4.0696, temperature 300, velocity 25 in the source CSV. '
            'Depth is normalized by the maximum held-out loading depth. Overall results '
            'across 18 folds and 5 seeds are R squared 0.957 plus or minus 0.040 and '
            'mean absolute error 7.07 nN. The nanoindentation drawing is schematic.</desc>',
            '<metadata>Sources: revision_models.py; revision_data.py; '
            'generate_figure_data.py; Indent_AlCuNiTiZr.csv; '
            'results/figure_data/fig1_loading_branch.npz (y_true_new, y_pred_new); '
            'response_tables/Table1_model_comparison_full_budget.csv. '
            'Plot provenance: EnergyPhasePINN, corrected time-ordered loading extraction, '
            'LOCO fold 0, seed 0, epochs=800. All 557 observations and predictions retained. '
            'Prediction polyline connects saved values in original loading order; no '
            'smoothing or fitted display curve. Input depth units are intentionally '
            'avoided by plotting delta/delta_max. Regime names denote model components, '
            'not measured microstructural phase fractions. R squared uncertainty is the '
            'standard deviation across 90 fold/seed runs. Figure generated by '
            'paper_figures/build_graphical_abstract.py.</metadata>',
            '<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" '
            'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
            f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{INK}"/></marker>'
            '<clipPath id="plot-clip"><rect x="1140" y="298" width="388" '
            'height="245"/></clipPath>'
            '<clipPath id="alloy-clip"><path d="M 86 373 H 174 '
            'Q 246 411 318 373 H 412 V 490 H 86 Z"/></clipPath></defs>',
        ]
        self.rect(0, 0, W, H, "#FFFFFF")

    def add(self, value):
        self.parts.append(value)

    def text(self, x, y, label, size=24, fill=INK, weight=400,
             anchor="start", raw=False, **attrs):
        extra = " ".join(f'{k.replace("_", "-")}="{v}"' for k, v in attrs.items())
        label = label if raw else html.escape(str(label))
        self.add(f'<text x="{x}" y="{y}" font-size="{size}" fill="{fill}" '
                 f'font-weight="{weight}" text-anchor="{anchor}" {extra}>{label}</text>')

    def rect(self, x, y, w, h, fill, stroke="none", r=0, sw=1.5):
        self.add(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" '
                 f'rx="{r}" fill="{fill}" stroke="{stroke}" stroke-width="{sw}"/>')

    def line(self, x1, y1, x2, y2, color=BORDER, sw=2, arrow=False, dash=None):
        attrs = ' marker-end="url(#arrow)"' if arrow else ""
        if dash:
            attrs += f' stroke-dasharray="{dash}"'
        self.add(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
                 f'stroke="{color}" stroke-width="{sw}"{attrs}/>')

    def path(self, d, stroke=INK, sw=2, fill="none", **attrs):
        extra = " ".join(f'{k.replace("_", "-")}="{v}"' for k, v in attrs.items())
        self.add(f'<path d="{d}" fill="{fill}" stroke="{stroke}" '
                 f'stroke-width="{sw}" stroke-linejoin="round" '
                 f'stroke-linecap="round" {extra}/>')

    def circle(self, x, y, r, fill, stroke="none", sw=1):
        self.add(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{fill}" '
                 f'stroke="{stroke}" stroke-width="{sw}"/>')

    def write(self, path):
        content = "\n".join(self.parts + ["</svg>"]) + "\n"
        ET.fromstring(content)
        path.write_text(content, encoding="utf-8")


def sub(label):
    return f'<tspan baseline-shift="sub" font-size="70%">{label}</tspan>'


def sup(label):
    return f'<tspan baseline-shift="super" font-size="70%">{label}</tspan>'


def source_curve():
    loading = data.keep_loading(data.load())
    heldout = loading.loc[data.group_id(loading) == 0]
    arrays = np.load(ROOT / "results/figure_data/fig1_loading_branch.npz")
    measured = heldout["Force"].to_numpy()
    # Verify both length and row alignment, rather than assuming the saved force
    # values belong to this particular curve or to a depth-sorted version.
    np.testing.assert_allclose(arrays["y_true_new"], measured, rtol=2e-6, atol=1e-5)
    assert len(heldout) == len(arrays["y_pred_new"]) == 557
    depth = heldout["Depth"].to_numpy()
    assert np.all(np.diff(depth) >= 0)
    assert data.check_time_ordering(data.load()) == []
    assert (ROOT / "response_tables/Table1_model_comparison_full_budget.csv").is_file()
    for values in (arrays["y_true_new"], arrays["y_pred_new"]):
        assert np.isfinite(values).all()
        assert values.min() >= 0 and values.max() <= 150, "Plot limits would clip data"
    return depth / depth.max(), arrays["y_true_new"], arrays["y_pred_new"]


def panel_label(s, x, number, label):
    s.text(x, 209, number, size=23, fill=MUTED)
    s.text(x + 44, 209, label, size=27, weight=700)


def draw_indent(s):
    # A sphere indenting a multicomponent lattice. Geometry, particle positions,
    # and colors are illustrative and deliberately labeled as a schematic.
    s.circle(248, 318, 77, "#E9EFF3", INK, 2.5)
    s.path("M 197 277 A 60 60 0 0 1 265 251",
           "#FFFFFF", 5)
    s.line(248, 246, 248, 309, INK, 2.5, arrow=True)
    s.text(277, 275, "F, δ", size=27)
    s.path("M 86 373 H 174 Q 246 411 318 373 H 412 V 490 H 86 Z",
           BORDER, 2, PALE_BLUE)
    palette = [BLUE, TEAL, ORANGE, "#8396A8", "#9A78A3"]
    s.add('<g clip-path="url(#alloy-clip)">')
    for row in range(5):
        for col in range(12):
            x = 96 + col * 29 + (14.5 if row % 2 else 0)
            y = 379 + row * 27
            if col < 11:
                s.line(x, y, x + 29, y, "#D0DBE2", 1.4)
            if row < 4:
                dx = 14.5 if row % 2 == 0 else -14.5
                s.line(x, y, x + dx, y + 27, "#D0DBE2", 1.4)
            s.circle(x, y, 6.2, palette[(row * 7 + col * 3) % 5])
    s.add("</g>")
    s.path("M 86 373 H 174 Q 246 411 318 373 H 412", INK, 2.5)
    s.text(249, 524, "Nanoindentation · schematic", size=22, fill=MUTED, anchor="middle")
    s.text(64, 575, "Depth δ  ·  grain size g", size=26)
    s.text(64, 611, "Temperature T  ·  velocity v", size=26)
    s.text(64, 649, "Time-ordered loading branch", size=23, fill=MUTED)


def draw_potential(s):
    cards = [(551, 144, "Elastic", "e", BLUE, PALE_BLUE),
             (710, 144, "Plastic", "p", TEAL, PALE_TEAL),
             (869, 164, "Hardening", "h", ORANGE, PALE_WARM)]
    for x, width, label, symbol, color, pale in cards:
        s.rect(x, 254, width, 93, pale, BORDER, r=9)
        s.rect(x, 254, width, 5, color, r=2)
        s.text(x + width / 2, 291, label, size=24, fill=color,
               weight=700, anchor="middle")
        s.text(x + width / 2, 327, f'U{sub(symbol)}(δ)', size=29,
               anchor="middle", raw=True, font_family=MATH_FONT)
        cx = x + width / 2
        s.line(cx, 347, cx, 367, color, 2.2)
    s.path("M 623 367 H 951 M 782 367 V 420", INK, 2.2,
           marker_end="url(#arrow)")
    s.rect(628, 377, 318, 28, "#FFFFFF")
    s.text(788, 399, "Smooth regime weights", size=23, fill=MUTED, anchor="middle")
    s.rect(551, 425, 482, 99, PALE_BLUE, BORDER, r=10)
    s.text(792, 458, "Scalar loading potential", size=23,
           fill=MUTED, anchor="middle")
    s.text(792, 498, f'U = ∑{sub("j")} w{sub("j")}U{sub("j")} + U{sub("res")}',
           size=33, weight=400, anchor="middle", raw=True, font_family=MATH_FONT)
    s.line(792, 525, 792, 550, INK, 2.2, arrow=True)
    s.text(792, 594, "F̂ = ∂U / ∂δ", size=42, weight=700, anchor="middle",
           font_family=MATH_FONT)
    s.text(792, 631, "Full automatic differentiation", size=23,
           fill=MUTED, anchor="middle")
    s.text(792, 660, f'U{sub("res")}: learned residual energy', size=22,
           fill=MUTED, anchor="middle", raw=True)


def draw_curve(s, x, measured, predicted):
    x0, y0, pw, ph = 1140, 543, 388, 245
    max_force = 150
    px = lambda values: x0 + np.asarray(values) * pw
    py = lambda values: y0 - np.asarray(values) / max_force * ph
    s.circle(1150, 254, 4.5, MUTED)
    s.text(1166, 262, "MD", size=23)
    s.line(1284, 254, 1320, 254, BLUE, 3.5)
    s.text(1331, 262, "Prediction", size=23)
    s.text(1107, 291, "Force (nN)", size=23, fill=MUTED)
    for tick in (0, 50, 100, 150):
        y = float(py(tick))
        s.line(x0, y, x0 + pw, y, BORDER, 1.2)
        s.text(x0 - 13, y + 7, str(tick), size=22, fill=MUTED, anchor="end")
    for tick in (0, 0.5, 1):
        xt = float(px(tick))
        s.line(xt, y0, xt, y0 + 7, INK, 1.5)
        s.text(xt, y0 + 32, f"{tick:g}", size=22, fill=MUTED, anchor="middle")
    s.line(x0, y0 - ph, x0, y0, INK, 1.6)
    s.line(x0, y0, x0 + pw, y0, INK, 1.6)
    s.add('<g clip-path="url(#plot-clip)">')
    for xp, yp in zip(px(x), py(measured)):
        s.circle(f"{xp:.3f}", f"{yp:.3f}", 2.3, "#99A7B0")
    points = " ".join(f"{xp:.3f},{yp:.3f}" for xp, yp in zip(px(x), py(predicted)))
    s.add(f'<polyline points="{points}" fill="none" stroke="{BLUE}" '
          'stroke-width="3.8" stroke-linejoin="round" stroke-linecap="round"/>')
    s.add("</g>")
    s.text(x0 + pw / 2, 616, f'Normalized depth  δ / δ{sub("max")}',
           size=24, anchor="middle", raw=True)
    s.text(x0 + pw / 2, 650, "Held-out curve · fold 0, seed 0", size=22,
           fill=MUTED, anchor="middle")


def main():
    x, measured, predicted = source_curve()
    s = SVG()
    s.text(60, 45, "ENERGYPHASEPINN", size=20, fill=BLUE,
           weight=700, letter_spacing="2")
    s.text(60, 98, "Energy-based learning of nanoindentation", size=44, weight=700)
    s.text(60, 138, "AlCuNiTiZr high-entropy alloy", size=27, fill=MUTED)
    s.line(60, 164, 1540, 164, BORDER, 1.5)

    panel_label(s, 60, "01", "MD loading data")
    panel_label(s, 551, "02", "Energy-based model")
    panel_label(s, 1103, "03", "Unseen condition")
    draw_indent(s)
    draw_potential(s)
    draw_curve(s, x, measured, predicted)
    s.line(463, 460, 520, 460, INK, 2.4, arrow=True)
    s.line(1048, 460, 1090, 460, INK, 2.4, arrow=True)

    s.text(800, 713, "Energy–force consistency  ·  Interpretable regime weights",
           size=30, weight=700, anchor="middle")
    s.rect(60, 739, 1480, 89, PALE_BLUE, r=10)
    s.text(82, 774, "18 conditions → 14 train / 3 validation / 1 test per fold", size=24)
    s.text(82, 807, "Leave-one-condition-out: 18 folds × 5 seeds", size=23, fill=MUTED)
    s.line(975, 755, 975, 811, BORDER, 1.5)
    s.text(1003, 775, "R² = 0.957 ± 0.040", size=28, weight=700)
    s.text(1003, 807, "Mean ± SD across folds and seeds", size=22, fill=MUTED)
    s.text(1494, 775, "7.07 nN", size=28, weight=700, anchor="end")
    s.text(1494, 807, "Mean MAE", size=22, fill=MUTED, anchor="end")
    out = HERE / "graphical_abstract.svg"
    s.write(out)
    print(f"Wrote {out}")
    print(f"Verified {len(x)} held-out points (fold 0, seed 0); native SVG, no raster.")


if __name__ == "__main__":
    main()
